trigger:
  - deploy

resources:
  - repo: self

stages:
  - stage: BuildPushCMSImage
    displayName: Build & Push CMS To Registry
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            displayName: Build and Push
            inputs:
              containerRegistry: "Discover Holyrood Registry"
              repository: "discoverholyroodcms"
              command: "buildAndPush"
              Dockerfile: "$(Build.SourcesDirectory)/cms/Dockerfile.prod"
