name: Test Runner

on: [push]

jobs:
  End-to-End-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          working-directory: apps/client
          runTests: false
          build: npm run build
          start: npx cypress info

      - name: Save Build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: apps/client/.next
          if-no-files-found: error
  End-to-End-Test:
    runs-on: ubuntu-latest
    needs: End-to-End-Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: apps/client/.next

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: apps/client
          record: true
          parallel: true
          start: npm run start
