name: Test Runner

on: [push]

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: cd apps/client npm run build

      - name: Save Build Folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
          if-no-files-found: error

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          record: true
          parallel: true
          start: npm start
