name: Test Runner

on: [push]

jobs:
  End-to-End:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          working-directory: apps/client
          runTests: false
          build: npx cypress info && npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: apps/client
          build: npm run cy:runCI
          record: true
          parallel: true
          start: npm run start
